### ISSUE TITLE
Specific Python file is detected as C++

### ISSUE THREAD

**Issue by areyde** [go-enry/enry#1] opened 2020-04-23 15:02 UTC
Steps to reproduce on [this file](https://raw.githubusercontent.com/acidanthera/OpenCorePkg/165db12fa3edb53cfe47e5fcba64d5b67a3c457f/Debug/Scripts/x86_64_target_definition.py):

```sh
wget https://raw.githubusercontent.com/acidanthera/OpenCorePkg/165db12fa3edb53cfe47e5fcba64d5b67a3c457f/Debug/Scripts/x86_64_target_definition.py
./enry x86_64_target_definition.py
```

Got:

> x86_64_target_definition.py: 783 lines (761 sloc)
> type:      Text
> mime_type: text/x-c++src
> language:  C++
> vendored:  false

Expected detection of Python.

**Comment by bzz** [comment] 2020-04-23 15:50
Thank you for reporting @areyde ! That, indeed, looks very strange. I will take a lot over the next 1-2 days and get back to you.

**Comment by bzz** [comment] 2020-04-28 11:53
The reason this file is detected as C++ is because the [detection logic](https://github.com/github/linguist#how-linguist-works), first relies on "Vim or Emacs modeline" (as a way to overried everything else) and the second line of the file looks like

```
#===-- x86_64_target_definition.py -----------------------------*- C++ -*-===//
                                                                                                                ^^^^^^^^^
```

which looks very much like [emacs modline](https://www.gnu.org/software/emacs/manual/html_node/emacs/Choosing-Modes.html)

**Comment by bzz** [comment] 2020-04-28 13:27
Confirmed, this is consistent with original linguist behavior (after cloning the linguist v.7.9.0)
```
$ bundle install
$ LINGUIST_DEBUG=2 irb -I .

irb(main):016:0* blob = Linguist::FileBlob.new(File.join("samples", "Python/x86_64_target_definition.py"))
irb(main):018:0* match = Linguist.detect(blob)
=> #<Linguist::Language name=C++>
```

**Comment by bzz** [comment] 2020-04-28 15:17
I guess it may not be the most desired outcome for your use-case, @areyde so what I would suggest to do instead, if github/linguist behviour does not suite you: one should define a particular series of matching strategies that one wants, by overriding [`enry.DefaultStrategies`](https://pkg.go.dev/github.com/go-enry/go-enry/v2?tab=doc#pkg-variables) e.g dropping or changing the order of `GetLanguagesByModeline` to be after `GetLanguagesByExtension`.

In this case, the file will be detected as Python. I can add a flag to the CLI binary e.g `--skip-modline` as a sort-term solution, but that would only handle one case and not really provide a generic solution that can adjust the strategies order, exclude some, etc. 

At the same time a generic solution in CLI flags may be unnecessary complex, so we would not want to commit ourselves to maintain that in go-enry codebase.

This makes me think about how would we want to expose this customization in the (upcoming) Pyhton API 🤔 

Please, let me know what you think!

**Comment by bzz** [comment] 2020-06-09 09:08
Closing this issue as the question seems to be answered now.

**Closed by bzz** 2020-06-09 09:08 UTC
Labels: question, wontfix
